"""
势场探针 V3
修复：
1. 文本扩到100条（367→1000+ tokens，减少过拟合）
2. 特征压到3个独立的（消除共线性）
3. Bootstrap交叉验证r（比R²更稳）
4. 目标层L3（V2发现最可读）
"""

import numpy as np
import torch
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import RidgeCV
from scipy.stats import spearmanr
from transformers import GPT2LMHeadModel, GPT2Tokenizer
import warnings
warnings.filterwarnings('ignore')

# ── 100条多样文本 ──
TEXTS = [
    # 事实/科学 (20)
    "The capital of France is Paris, which has been the center of European culture for centuries.",
    "Water freezes at zero degrees Celsius under standard atmospheric pressure at sea level.",
    "The human brain contains approximately 86 billion neurons connected by trillions of synapses.",
    "Einstein published his theory of special relativity in 1905 at the age of twenty-six.",
    "DNA is a double helix structure made of four nucleotide bases: adenine, thymine, guanine, cytosine.",
    "The speed of light in a vacuum is approximately 299,792,458 meters per second.",
    "Photosynthesis converts carbon dioxide and water into glucose using sunlight energy.",
    "The periodic table currently contains 118 confirmed elements organized by atomic number.",
    "Black holes form when massive stars collapse under their own gravitational force.",
    "The Earth's magnetic field is generated by the movement of molten iron in the outer core.",
    "Quantum entanglement allows particles to correlate their states regardless of distance.",
    "The mitochondria is the powerhouse of the cell, producing ATP through cellular respiration.",
    "Tectonic plates move at roughly the same speed as fingernails grow, a few centimeters per year.",
    "The universe is estimated to be approximately 13.8 billion years old based on cosmic background radiation.",
    "Antibiotics work by disrupting bacterial cell wall synthesis or protein production mechanisms.",
    "Gravity waves were first directly detected in 2015 from merging black holes 1.3 billion light-years away.",
    "The human genome contains approximately 3 billion base pairs encoding around 20,000 genes.",
    "Volcanoes form at tectonic plate boundaries where magma pushes through the Earth's crust.",
    "The average distance from Earth to the Moon is 384,400 kilometers.",
    "Neurons communicate through electrochemical signals called action potentials.",

    # 推理/逻辑 (20)
    "If all mammals are warm-blooded and whales are mammals, then whales must be warm-blooded.",
    "The problem requires identifying constraints before attempting any solution strategy.",
    "Since the experiment failed twice with identical conditions, assumptions must be reconsidered.",
    "Given that prices rose while demand fell, supply must have decreased significantly.",
    "To prove this theorem we need to establish three separate lemmas as foundations.",
    "The argument has a hidden premise that contradicts the stated conclusion.",
    "Either the data is corrupted or the algorithm has a fundamental flaw in its logic.",
    "If this hypothesis is correct, then we should observe a measurable increase in temperature.",
    "The contradiction arises because two premises cannot both be true simultaneously.",
    "Inductive reasoning builds general conclusions from specific observed instances.",
    "The null hypothesis cannot be rejected based on the current statistical evidence alone.",
    "If A implies B and B implies C, then A necessarily implies C by transitivity.",
    "The experiment controls for confounding variables by randomizing the assignment of subjects.",
    "Correlation between variables does not establish a causal relationship between them.",
    "The logical fallacy here is assuming that temporal sequence implies causal relationship.",
    "Occam's razor suggests preferring the simpler explanation when evidence is equal.",
    "The paradox arises from a self-referential statement that cannot be consistently evaluated.",
    "Mathematical induction proves statements for all natural numbers through base and step.",
    "The counterexample disproves the universal claim by demonstrating a single exception.",
    "Deductive reasoning guarantees conclusions if premises are true and form is valid.",

    # 创意/文学 (20)
    "The old lighthouse stood alone against the darkening sea, its beam sweeping endlessly.",
    "She remembered the smell of rain on hot pavement, that particular summer melancholy.",
    "Dreams are the mind's rehearsal of possibilities it cannot yet fully articulate.",
    "The painting seemed to breathe, its colors shifting with every change of afternoon light.",
    "In the silence between notes, music discovers its truest and most profound expression.",
    "He walked through the city feeling invisible, a ghost among the rushing crowds.",
    "The snow fell softly, covering the garden in a silence that felt almost sacred.",
    "Words failed her in that moment, and the unsaid hung heavy between them like fog.",
    "The child laughed at something only she could see, lost in her private imagined world.",
    "Autumn stripped the trees bare, leaving only their essential architecture exposed.",
    "The letter arrived decades too late, carrying news that no longer mattered to anyone.",
    "She pressed the old photograph to her chest as if warmth could travel backward through time.",
    "The river had changed course over the years, abandoning its old path for a new one.",
    "Between the ticking seconds, entire lifetimes seem to pass unnoticed and unrecorded.",
    "The abandoned house held memories like pressed flowers, fragile and slowly fading.",
    "His laughter was the sound of someone who had learned to find joy in small, hidden things.",
    "The market smelled of spices and salt and something else she could not quite name.",
    "Stars appeared one by one as the dusk deepened into the velvet dark of true night.",
    "She had spent years building walls only to discover that she had walled herself inside.",
    "The music from the next room was the sound of a childhood she could barely remember.",

    # 代码/技术 (20)
    "def fibonacci(n): return n if n <= 1 else fibonacci(n-1) + fibonacci(n-2)",
    "The function iterates through the array and returns the index of the maximum element.",
    "Initialize the matrix with zeros then set diagonal elements to one for identity.",
    "The algorithm achieves O(n log n) complexity through recursive divide and conquer.",
    "SQL inner join combines rows from two tables where the join condition is satisfied.",
    "Binary search requires a sorted array and finds elements in logarithmic time.",
    "The neural network backpropagates gradients through layers using the chain rule.",
    "Hash tables provide constant time lookup by mapping keys to array indices directly.",
    "Recursion solves problems by breaking them into smaller identical subproblems.",
    "The garbage collector automatically frees memory that is no longer referenced.",
    "REST APIs communicate using standard HTTP methods like GET POST PUT DELETE.",
    "Docker containers package applications with their dependencies for consistent deployment.",
    "Version control systems track changes and enable collaboration across development teams.",
    "The cache stores frequently accessed data to reduce latency and improve performance.",
    "Asynchronous programming allows tasks to run concurrently without blocking execution.",
    "Regular expressions match patterns in text using special syntax and quantifiers.",
    "The stack data structure follows last in first out ordering for element access.",
    "Encryption transforms readable data into ciphertext using mathematical algorithms.",
    "Unit tests verify individual functions work correctly in isolation from other code.",
    "Compilation translates source code into machine instructions that the processor executes.",

    # 哲学/模糊/不确定 (20)
    "Maybe the answer lies somewhere between these two seemingly opposite positions.",
    "It is difficult to say with certainty whether consciousness is reducible to physics.",
    "The evidence suggests correlation but cannot definitively establish direct causation.",
    "Perhaps meaning emerges from complexity in ways that resist formal explanation.",
    "The question remains genuinely open and may not admit a single definitive answer.",
    "What we call reality may be shaped as much by perception as by external facts.",
    "Free will and determinism may not be as incompatible as they initially appear.",
    "The boundary between self and world is less clear than everyday experience suggests.",
    "Time may not flow uniformly but rather be a construct of conscious experience.",
    "Whether mathematics is discovered or invented remains a genuinely contested question.",
    "Beauty resists precise definition yet remains recognizable across cultures and eras.",
    "The self may be less a fixed entity than an ongoing narrative we construct and revise.",
    "Moral intuitions feel compelling but their ultimate justification remains unclear.",
    "Language shapes thought in ways that may be difficult to fully step outside of.",
    "The gap between subjective experience and objective description may be unbridgeable.",
    "Whether other minds exist is something we cannot verify but also cannot doubt in practice.",
    "Progress in science raises as many questions as it resolves about the nature of things.",
    "Art communicates something that resists translation into purely propositional terms.",
    "The relationship between mind and brain remains one of the deepest open problems.",
    "Perhaps some questions are not meant to be answered but to be lived with carefully.",
]

print(f"文本池: {len(TEXTS)} 条")
print("="*60)

# ── 加载模型 ──
print("加载GPT-2...")
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
tokenizer.pad_token = tokenizer.eos_token
model = GPT2LMHeadModel.from_pretrained('gpt2', output_hidden_states=True)
model.eval()
device = 'cuda' if torch.cuda.is_available() else 'cpu'
model = model.to(device)
print(f"设备: {device}")

# ── 收集数据 ──
print("\n收集激活 + logits...")
all_hidden = {i: [] for i in range(13)}
all_logits = []

with torch.no_grad():
    for idx, text in enumerate(TEXTS):
        tokens = tokenizer(text, return_tensors='pt', truncation=True, max_length=64)
        tokens = {k: v.to(device) for k, v in tokens.items()}
        outputs = model(**tokens)
        for layer_idx in range(13):
            all_hidden[layer_idx].append(outputs.hidden_states[layer_idx][0].cpu().numpy())
        all_logits.append(outputs.logits[0].cpu().numpy())
        if (idx+1) % 20 == 0:
            print(f"  {idx+1}/{len(TEXTS)}")

X_hidden = {i: np.vstack(all_hidden[i]) for i in range(13)}
X_logits  = np.vstack(all_logits)
X_prob    = torch.softmax(torch.tensor(X_logits), dim=-1).numpy()
N = X_hidden[0].shape[0]
print(f"总token数: {N}")

# ── 3个独立特征 ──
entropy    = -np.sum(X_prob * np.log(X_prob + 1e-10), axis=1)   # 不确定性
logit_skew = (X_logits.max(axis=1) - 2*np.median(X_logits, axis=1) + X_logits.min(axis=1))  # 分布偏度
logit_var  = X_logits.var(axis=1)                                 # 分布宽度

X_feat = np.column_stack([entropy, logit_skew, logit_var])
X_feat_s = StandardScaler().fit_transform(X_feat)

# 检查相关性
r_es, _ = spearmanr(entropy, logit_skew)
r_ev, _ = spearmanr(entropy, logit_var)
r_sv, _ = spearmanr(logit_skew, logit_var)
print(f"\n特征间相关性（越低越独立）:")
print(f"  entropy vs logit_skew: r={r_es:.3f}")
print(f"  entropy vs logit_var:  r={r_ev:.3f}")
print(f"  logit_skew vs logit_var: r={r_sv:.3f}")

# ── 辅助函数 ──
def get_pc1(X):
    return PCA(n_components=1).fit_transform(StandardScaler().fit_transform(X))[:, 0]

def bootstrap_r(y_true, y_pred, n=500, seed=42):
    rng = np.random.default_rng(seed)
    rs = []
    for _ in range(n):
        idx = rng.integers(0, len(y_true), len(y_true))
        r, _ = spearmanr(y_true[idx], y_pred[idx])
        rs.append(r)
    return np.array(rs)

# ── 跨层分析 ──
print("\n" + "="*60)
print("跨层分析（3特征 + Bootstrap CV）")
print("="*60)
print(f"  {'层':<5} {'r_entropy':>10} {'r_3feat':>10} {'95%CI':>18}  {'解释'}")
print("  " + "-"*60)

results_by_layer = []
for layer_idx in range(13):
    pc1 = get_pc1(X_hidden[layer_idx])

    # 单变量熵
    r_e, _ = spearmanr(pc1, entropy)

    # 3变量Ridge
    ridge = RidgeCV(alphas=[0.01, 0.1, 1.0, 10.0, 100.0], cv=5)
    ridge.fit(X_feat_s, pc1)
    pc1_pred = ridge.predict(X_feat_s)
    r_m, _ = spearmanr(pc1, pc1_pred)

    # Bootstrap
    boot = bootstrap_r(pc1, pc1_pred)
    ci_lo, ci_hi = np.percentile(boot, [2.5, 97.5])

    results_by_layer.append({
        'layer': layer_idx, 'r_entropy': r_e,
        'r_multi': r_m, 'ci_lo': ci_lo, 'ci_hi': ci_hi,
        'pc1': pc1, 'pc1_pred': pc1_pred, 'alpha': ridge.alpha_
    })

    flag = '★' if abs(r_m) > 0.7 else ('✓' if abs(r_m) > 0.5 else ' ')
    print(f"  L{layer_idx:<4} {r_e:>+10.4f} {r_m:>+10.4f} [{ci_lo:+.3f},{ci_hi:+.3f}]  {flag}")

# ── 目标层详细分析（最佳层）──
best = max(results_by_layer, key=lambda x: abs(x['r_multi']))
TARGET = best['layer']
print(f"\n最佳可读层: L{TARGET}  r={best['r_multi']:.4f}  [α={best['alpha']}]")

# 用L3做详细展示（V2已知最佳）
L3 = results_by_layer[3]
PC1_truth = L3['pc1']
PC1_pred  = L3['pc1_pred']
boot_L3   = bootstrap_r(PC1_truth, PC1_pred)

print(f"\nL3详细:")
print(f"  r = {L3['r_multi']:.4f}")
print(f"  Bootstrap 95%CI: [{np.percentile(boot_L3,2.5):.4f}, {np.percentile(boot_L3,97.5):.4f}]")
print(f"  Bootstrap均值:   {boot_L3.mean():.4f}")
print(f"  Bootstrap std:   {boot_L3.std():.4f}")

# ── 按文本类型分析 ──
print("\n按文本类型分析（每类20条）:")
type_names = ['事实/科学', '推理/逻辑', '创意/文学', '代码/技术', '哲学/模糊']
# 估算每条文本占的token数（大约12-15个token/条，取实际切分）
tokens_per_text = []
for text in TEXTS:
    toks = tokenizer(text, truncation=True, max_length=64)
    tokens_per_text.append(len(toks['input_ids']))

token_boundaries = np.cumsum([0] + tokens_per_text)

for type_idx in range(5):
    start_text = type_idx * 20
    end_text   = start_text + 20
    tok_start  = token_boundaries[start_text]
    tok_end    = token_boundaries[end_text]
    seg_truth  = PC1_truth[tok_start:tok_end]
    seg_pred   = PC1_pred[tok_start:tok_end]
    if len(seg_truth) > 5:
        r_seg, _ = spearmanr(seg_truth, seg_pred)
        print(f"  {type_names[type_idx]:<10}: r={r_seg:.4f}  n={len(seg_truth)} tokens")

# ── 可视化 ──
print("\n生成可视化...")
fig, axes = plt.subplots(2, 3, figsize=(18, 11))
fig.patch.set_facecolor('#0d1117')

def style_ax(ax, title):
    ax.set_facecolor('#0a0a0f')
    ax.set_title(title, color='white', fontsize=10, pad=8)
    ax.tick_params(colors='#666', labelsize=8)
    for sp in ax.spines.values():
        sp.set_edgecolor('#333')

# 1. 跨层r值
ax = axes[0, 0]
style_ax(ax, '跨层可读性（3特征 vs 熵单变量）')
layers = [r['layer'] for r in results_by_layer]
r_e_all = [r['r_entropy'] for r in results_by_layer]
r_m_all = [r['r_multi']   for r in results_by_layer]
ci_lo_all = [r['ci_lo'] for r in results_by_layer]
ci_hi_all = [r['ci_hi'] for r in results_by_layer]
ax.fill_between(layers, ci_lo_all, ci_hi_all, alpha=0.2, color='#2ecc71', label='95% CI')
ax.plot(layers, r_m_all, 's-', color='#2ecc71', linewidth=2, markersize=6, label='3特征')
ax.plot(layers, r_e_all, 'o--', color='#f39c12', linewidth=1.5, markersize=5, label='熵单变量')
ax.axhline(0.5, color='white', linewidth=0.8, linestyle=':', alpha=0.5)
ax.axhline(0.7, color='#e74c3c', linewidth=0.8, linestyle=':', alpha=0.5)
ax.axhline(0, color='#444', linewidth=0.8)
ax.text(12.1, 0.51, '0.5', color='#888', fontsize=7)
ax.text(12.1, 0.71, '0.7', color='#e74c3c', fontsize=7)
ax.set_xlabel('Layer', color='#888')
ax.set_ylabel('Spearman r', color='#888')
ax.legend(fontsize=8, facecolor='#111', labelcolor='white')

# 2. L3散点图
ax = axes[0, 1]
style_ax(ax, f'L3: 激活PC1 vs 行为预测 (r={L3["r_multi"]:.3f})')
# 按文本类型着色
type_colors = []
for ti, n in enumerate(tokens_per_text):
    type_colors.extend([ti // 20] * n)
type_colors = np.array(type_colors[:len(PC1_truth)])
cmap = plt.cm.get_cmap('tab10', 5)
for ti, tname in enumerate(type_names):
    mask = type_colors == ti
    if mask.sum() > 0:
        ax.scatter(PC1_truth[mask], PC1_pred[mask], alpha=0.5, s=12,
                   color=cmap(ti), label=tname)
lims = [min(PC1_truth.min(), PC1_pred.min()), max(PC1_truth.max(), PC1_pred.max())]
ax.plot(lims, lims, 'w--', alpha=0.3, linewidth=1)
ax.set_xlabel('激活PC1（真实）', color='#888')
ax.set_ylabel('行为预测', color='#888')
ax.legend(fontsize=7, facecolor='#111', labelcolor='white')

# 3. Bootstrap分布
ax = axes[0, 2]
style_ax(ax, f'Bootstrap r分布 (L3, n=500)')
ax.hist(boot_L3, bins=40, color='#3498db', alpha=0.8, edgecolor='none')
ax.axvline(L3['r_multi'], color='#e74c3c', linewidth=2, label=f'r={L3["r_multi"]:.3f}')
ax.axvline(np.percentile(boot_L3, 2.5), color='#f39c12', linewidth=1.5, linestyle='--')
ax.axvline(np.percentile(boot_L3, 97.5), color='#f39c12', linewidth=1.5, linestyle='--', label='95%CI')
ax.axvline(0.5, color='white', linewidth=1, linestyle=':', alpha=0.5)
ax.set_xlabel('Spearman r', color='#888')
ax.set_ylabel('频次', color='#888')
ax.legend(fontsize=8, facecolor='#111', labelcolor='white')

# 4. 3特征的单变量r（各层）
ax = axes[1, 0]
style_ax(ax, '3特征单独贡献（L3）')
feat_labels = ['entropy', 'logit_skew', 'logit_var']
feat_data   = [entropy, logit_skew, logit_var]
feat_colors = ['#3498db', '#e74c3c', '#2ecc71']
PC1_L3 = results_by_layer[3]['pc1']
for fi, (fname, fdata, fc) in enumerate(zip(feat_labels, feat_data, feat_colors)):
    r_f, _ = spearmanr(PC1_L3, fdata)
    ax.barh(fname, abs(r_f), color=fc, alpha=0.85)
    ax.text(abs(r_f)+0.01, fi, f'{r_f:+.3f}', va='center', color='white', fontsize=10)
ax.set_xlabel('|Spearman r|', color='#888')
ax.set_xlim(0, 0.8)

# 5. V1→V2→V3进展
ax = axes[1, 1]
style_ax(ax, 'V1 → V2 → V3 进展')
vers   = ['V1\n(Logit PC1)', 'V1\n(熵)', 'V2\n(11特征)', 'V3\n(3特征)']
r_vers = [0.2802, 0.4261, 0.6249, L3['r_multi']]
bcolors = ['#e74c3c', '#f39c12', '#3498db', '#2ecc71']
bars = ax.bar(vers, [abs(r) for r in r_vers], color=bcolors, alpha=0.85, width=0.5)
for bar, r in zip(bars, r_vers):
    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.01,
            f'r={r:.3f}', ha='center', color='white', fontsize=10, fontweight='bold')
ax.axhline(0.5, color='white', linewidth=0.8, linestyle='--', alpha=0.4)
ax.axhline(0.7, color='#e74c3c', linewidth=0.8, linestyle='--', alpha=0.4)
ax.set_ylim(0, 0.95)
ax.set_ylabel('|Spearman r|', color='#888')

# 6. 总结
ax = axes[1, 2]
ax.set_facecolor('#0a0a0f')
ax.axis('off')
r3 = L3['r_multi']
ci_lo3 = np.percentile(boot_L3, 2.5)
ci_hi3 = np.percentile(boot_L3, 97.5)
best_layer_r = max(r['r_multi'] for r in results_by_layer)
best_layer_n = max(results_by_layer, key=lambda x: x['r_multi'])['layer']
status = '✓ 强行开源成立' if r3 > 0.5 else '△ 部分成立'
lines = [
    "=== 势场探针 V3 结果 ===",
    "",
    f"样本: {len(TEXTS)}条文本, {N} tokens",
    f"特征: 3个独立行为特征",
    "",
    f"L3 r = {r3:.4f}",
    f"Bootstrap CI: [{ci_lo3:.3f},{ci_hi3:.3f}]",
    "",
    f"最佳层: L{best_layer_n}  r={best_layer_r:.4f}",
    "",
    "进展:",
    f"  V1(logit): 0.280",
    f"  V1(熵):    0.426",
    f"  V2(11feat):0.625*",
    f"  V3(3feat): {r3:.3f}",
    "",
    status,
    "",
    "* V2过拟合，V3 Bootstrap验证",
]
for i, line in enumerate(lines):
    color = '#2ecc71' if line.startswith('✓') else ('#f39c12' if line.startswith('△') else 'white')
    ax.text(0.05, 0.97-i*0.062, line, transform=ax.transAxes,
            color=color, fontsize=9, va='top', fontfamily='monospace')

fig.suptitle("势场探针 V3 — 3独立特征 + Bootstrap验证",
             color='white', fontsize=13, y=1.01)
plt.tight_layout()
plt.savefig('field_probe_v3.png', dpi=120, bbox_inches='tight', facecolor='#0d1117')
plt.show()

print("\n" + "="*60)
r_best = max(r['r_multi'] for r in results_by_layer)
print(f"核心结果: L3 r={L3['r_multi']:.4f}  最佳层 r={r_best:.4f}")
print(f"Bootstrap CI: [{ci_lo3:.3f}, {ci_hi3:.3f}]")
print(f"r > 0.7且CI下界 > 0.5 → 可以攻闭源模型了")
print("="*60)
